packages:
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  body-parser@<2.2.1: ">=2.2.1"
  glob@>=10.2.0 <10.5.0: ">=10.5.0"
  js-yaml@<3.14.2: ^3.14.2
  js-yaml@>=4.0.0 <4.1.1: ">=4.1.1"
